		function loadstorymessages(){var storymessages = ["Right click for thrust, left click to shoot, and point the mouse in whatever direction you want to face, and don't forget that you have to slow down at the other end.  Going anywhere in particular is more complicated, and if you wander around without a destination, you'll find what space is really made made of:  Nothing.",
		"You can cycle navigation modes between targeting planets, targeting stations, and off with the N key.  < and > will cycle through available nav targets.  The bottom right compass will point towards your nav target, and indicates name and distance.  The chart to the left gives more information if you're interested.  Try selecting planet Merz.",
			"Great!  That's where you'll be going next.  But to help you know your place in the universe, your HUD also has a map.  The M key cycles between a full-screen display, a corner display, and off.  I recommend the corner.  You can zoom in and out with the + and - keys.",
			"The yellow rectangle in the center of the map is where you and the space you can see are located.  Planets, moons, and stations are drawn on the map, and planetary orbits are shown with grey lines.  Try zooming way out (- key) so that the whole system is in view.",
			"Nifty, right?  OK, so we're not going nearly that far away, so zoom back in on us and the inner planets.",
			"OK, so thats basically what you need to fly this burrito to Merz.  Just do a close flyby--the rest is automatic--and then head back to The Merry Merzian.",
			"Good job.  Now get back to the Merry Merzian.  Remember you can use your nav (N, <, >) computer to find the station.  When you're close you'll dock automatically.",
			"Alright, good job.  I suppose we should talk about the 'bots.  Most planets and moons have hostile Umobots.  They orbit their host planets and shoot at any ships that come near.  Around Merz they aren't particularly dangerous, but each planet has it's own breed of bot, and most are more dangerous than the Merz bots.",
			"Bots can be destroyed (in fact the Institute pays bounties for this), but replacements are never far behind.  Space stations are built trailing or leading planets in solar orbits to keep them farther away from the Umobots in planetary orbit.",
			"No one knows where they came from, or why they suddenly started appearing 30 years ago.  But life off-world has changed dramatically since they came.  Most of your ships systems are reverse engineered Umobot pieces, and a whole new industry has developed around both fighting and studying the 'bots",
			"You better learn a thing or two about combat before I send you anywhere more dangerous, eh?  The top left corner of your HUD has 4 important indicators.  At the top the green bar indicates your ship's health.  It's a basic measure of how close you are to blowing up.  Don't blow up.",
			"The next blue bar is your shield strength.  Your shield is a fast regenerating energy barrier that prevents your ship from being damaged by occasional minor hits.  Don't enter combat without a full shield, and get out if it ever goes down to 0.  A weak shield will still reduce the damage you take compared to no shield at all.",
			"The next red bar is your weapons energy.  The ship has capacitors to provide the burst current that the ships reactor can't directly provide.  The red bar indicates their energy level.",
			"Finally, the orange bar at the bottom shows your thruster energy level.  Just like your weapons, the ship's thrust capacitors recharge quickly with power from the reactor.  Don't get caught in a fight without any go-juice to spare for escape or evasive maneuvers.",
			"Below the status bars is a weapons indicator highlighting your current weapon in green, and showing available weapons in white (just weapon 1 for now).",
			"The last part of the HUD we need to talk about is the targeting computer.  Your radar can detect enemies within a certain distance (4000p, as shown by the green circle on your map), and tell you useful information about them.  Use the [ and ] keys to select targets.  In visual range, you'll also see a targeting reticle around your target.",
			"Speaking of which, why don't you do me a favor and destroy a particular bot in Merz orbit?  The name is ",
			"Alright good job.  Now before you get carried away come back to the station and I'll fit your ship with something a little more powerful.",
			"Alright wait here for a moment while I work on your ship.  Your basic blaster, while not having any extraordinary capabilities, is energy efficient and effective for most situations.  The Mine launcher, is extraordinarily powerful but only useful in very special circumstances.",
			"New weapons an upgrades can be purchased at stations like the Merry Merzian, but I'm installing the mine launcher for free.  Go ahead and launch, it should be ready.",
			"OK now switch to weapon 2 and give it a shot.",
			"Watch how slowly it launches.  Be careful not to fly into it!  The mine doesn't really get launched so much as dropped off with a gentle push.  It's up to to pilot to fly his ship to whatever momentum the mine needs, release and fly away.  The upshot is that the mine is both powerful and long-lasting.",
			"Pilots sometimes will sometimes drop a mine and fly into combat behind it, or leave a mine in orbit of a planet in a target-rich environment.  Having a mine (or any bomb) active doesn't stop you from switching to and using other weapons without terminating the mine.",
			"Although not usually used for picking off faraway targets, the mine technically has the longest range (by far) of any weapon due to its long timer, provided the pilot provides a bit of speed for the mine.",
			"Many weapons, including the mine, have an upgrade that allows you to detonate the mine with a second click.  For the mine this is highly recommended.",
			"In space, bling is everything.  At stations like the Merry Merzian you can spend it on repairs or upgrades.  You get paid in bling by the Institute for destroying umo bots, and more for salvaging their bling.",
			"Stations have Buy, Sell, and Work menus, which you can cycle through with the Backspace key.  Aside from missions at the Work menu, you can buy and sell commodities for profit.",
			"If you don't mind being told what to do, missions usually offer more bling for your time than a comparable activity would earn without taking a mission.  You may have noticed an extra $200 after the delivery, and $400 after destroying the bot for me.",
			"Mission payments are paid out in addition to any bling you might make from standard institute salvage, bounties, or other concurrent activities.  Always be on the lookout for ways to get paid twice.",
			"Speaking of which, I've got a package for Jojo's (trailing Jupe), and I'll pay $800 for it to be delivered.  You'll probably want to use boosters.",
			"Boosters provide a single-use burst of speed for faster travel among the outer planets.  They're sold in pairs, because for every one you use to get moving towards your destination, you'll need another to slow down when you get there.",
			"You can cycle between booster types with the B key, and fire the booster with the G key.  Your ship comes with 8 type 1 boosters, and you can buy more at certain traders.",
			"Make sure you're pointing the right way before you fire the booster, and make sure you packed an extra for braking.  You might also need another pair to get back ",
			"Also, Try not to tangle with the local 'bots around Jupe and moons, they're more dangerous than the 'bots around Merz by far.  The station is far enough away that you shouldn't need to engage them.",
			"Nice work.  I'm going to recommend you to Bill.  Bill's Bits trails Earf, 3rd planet from the sun.  You can go there and work for him, or just take time to explore or seek your own fortune.",
			"Welcome to Earf!  My name is Bill Maker.  Dudeman tells me you're learning to fly, and I'm looking for cheap labor.",		
			"Now I know Dudeman tends to gloss over the finer points of flying so I'm going to fill in a few details for you.",
			"I'm sure you've discovered that stopping at your destination is half the challenge of getting there.  Many pilots will count the number of times they click their thrusters towards their destination, and then click the same number of times facing away from it to stop.",
			"This is of course doubly true when using boosters--You need to make sure you have at least as many reserved for stopping as you used to get moving in the first place.",
			"As far as your weapons go, most of them can only maintain a single bomb.  If you fire with a bomb already out from that weapon, you'll terminate the existing bomb and create a new one.  So be sure to wait for your bomb to hit and fully explode before shooting again. ",
			"You can, however, switch to a different weapon and fire it without recalling or refreshing the bomb you have out.  This is most useful for the mine, which has a very long timer.",
			"A few weapons like w6 and w8 fire continuously when the mouse button is held, and they don't have that limitation.",
			"Aside from the remote detonator upgrade, there are a myriad of different ways to upgrade weapons, and they can all be combined as you see fit.  However, each time you buy an upgrade, the cost of the next one for that weapon will be double.",
			"Not every upgrade will be equally beneficial to every weapon, and sometimes it might pay to wait until you encounter a station with the upgrade(s) that you REALLY want before you spend your bling and drive up the costs.",
			"The bots around the inner planets aren't as dangerous as those around outer planets like Jupe and Tern, but they're bad enough that we can't ignore them completely.  ",
			"There's been an initiative to build a moon base with blasters to keep their numbers down, but its a costly endeavor and no one wants to see it blown up by bots before it's finished.",
			"I've been hoarding materials for a while now, and I'm close to having what I need, but I still need to somehow build the thing without taking any hits until the shield generator comes up. ",
			"There's a guy I know who shares my enthusiasm for this base, and he's actually collected enough parts that we could build it.  However, he and all the gear are out on the edge of the system in Dangustown",
			"The bots are very dangerous out there, but you probably won't need to fight any to make the pickup.  You will, however need 10 units of cargo space to take a crate, and 20 to bring both crates in one trip.",
			"Welcome to Dangustown.  Make yourself at home.  We have a saying out here--It's YOUR Anus--which a lot of people blurt out whenever the planet and surrounding community are mentioned.",
			"Bill mentioned you would be coming.  You'll need at least 10 units of cargo space to take a crate, and I've got 2 crates.",
			"First crate is loaded, but you'll have to come back for the other one.",
			"First crate delivered.  I just need you to go back and pick up one more crate from Dangustown",
			"2nd crate is loaded. Tell Bill I said good luck.",
			"Great, both crates are delivered.   I'll need some time to sort through all this and build up pieces, so I'd suggest you spend some of those credits on your ship and maybe do some work from the mission board in the meantime.",
			"We're ready to start installing the Earf Defense platform.  We're going to start with the mounting pillar.  Stop by Bill's when you're ready to help.  ",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"filler.",
			"Yo Yo this is the last message."
			];
			return storymessages;
			}